name = "aurion-api"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = true

[vars]
OWNER_EMAIL = "ramonjunio07@gmail.com"
OWNER_NAME = "Ramon Junio Araujo Pereira"
ALLOWED_ORIGINS = "https://aurionfinance.com.br,https://www.aurionfinance.com.br"

[[d1_databases]]
binding = "DB"
database_name = "aurion-db"
database_id = "2f6f2dff-8a1c-4daa-9263-586e1efc1b38"

[triggers]
crons = ["*/15 * * * *"]

[observability]
enabled = true
