/* Catálogo do tour da página Tributação. Cada passo tem 4 blocos (por que existe, o que faz, o que representa,
 * por que este número). Os números vêm de tour_explain.js, que lê os mesmos dados que desenharam a tela. */
import * as X from "./tour_explain.js";

export const TOUR_TRIBUTACAO_VERSAO = "1";
const o = c => ({ demo: c.demo });
const n = v => +v || 0;
const regraTxt = (c, code) => { const r = (c.rules?.items || []).find(x => x.code === code); return r?.sources?.length ? ` Fontes da regra: ${r.sources.map(s => s.id + " — " + s.title).join("; ")}.` : ""; };
const temDarf = c => (c.t.months || []).some(m => m.darf);
const exemplo = c => X.maiorVenda(c.t);

export function stepsTributacao() {
  return [
    /* ---------------------------------------------------------------- A. abertura e barra superior */
    { id: "boas-vindas", secao: "Abertura", titulo: "Bem-vindo à Tributação",
      porque: "Quem investe na bolsa precisa apurar o imposto todo mês, sozinho. Errar ou atrasar gera multa e juros.",
      faz: "Mostra a apuração mensal, o que é isento, as guias de pagamento e a origem de cada número.",
      representa: c => X.abertura(c.t, o(c)) },
    { id: "menu", secao: "Abertura", target: '[data-tour="menu"]', titulo: "Menu",
      porque: "Tributação é uma parte do AURION; patrimônio, finanças e alertas usam os mesmos dados.",
      faz: "Leva às outras áreas do aplicativo. No celular, abre a gaveta com todas as páginas.",
      representa: "A navegação principal da sua conta." },
    { id: "logo", secao: "Abertura", target: '[data-tour="logo"]', titulo: "Logotipo",
      porque: "Um atalho fixo para sair do aplicativo e voltar ao site.",
      faz: "Abre a página inicial do site do AURION. Sua sessão continua ativa.",
      representa: "A marca AURION." },
    { id: "tema", secao: "Abertura", target: '[data-tour="tema"]', titulo: "Tema claro, escuro ou automático",
      porque: "Conforto de leitura: de dia, à noite ou acompanhando o sistema.",
      faz: "Troca só a aparência. Nenhum número ou cálculo muda.",
      representa: "Sua preferência visual, guardada neste navegador." },
    { id: "sino", secao: "Abertura", target: '[data-tour="sino"]', titulo: "Avisos",
      porque: "Prazos de DARF e dados faltando não podem passar despercebidos.",
      faz: "Abre a lista de avisos. O ponto vermelho indica avisos não lidos.",
      representa: "Notificações da conta: vencimentos, segurança e alertas.",
      numero: c => { const pr = (c.t.months || []).filter(m => m.darf && m.darf.status !== "pago").sort((a, b) => a.darf.vencimento.localeCompare(b.darf.vencimento))[0];
        return pr ? X.SELO_DEMO.repeat(c.demo ? 1 : 0) + (pr.darf.status === "vencido" ? `Há guia vencida: ${X.mesBR(pr.month)}, ${X.brl(pr.darf.valor)}, venceu em ${X.dataBR(pr.darf.vencimento)}.` : `O aviso tributário mais próximo é a guia de ${X.mesBR(pr.month)}: ${X.brl(pr.darf.valor)}, vencimento ${X.dataBR(pr.darf.vencimento)}.`) : null; } },
    { id: "avatar", secao: "Abertura", target: '[data-tour="avatar"]', titulo: "Sua conta",
      porque: "Reúne o que é pessoal: dados, plano, privacidade e saída segura.",
      faz: "Abre Configurações, Privacidade, Planos e Sair.",
      representa: "A sua conta, identificada pela inicial do nome." },

    /* ---------------------------------------------------------------- B. avisos no topo */
    { id: "aviso-exemplo", secao: "Avisos", target: '[data-tour="aviso-exemplo"]', when: c => !!c.t.sample, titulo: "Exemplo ilustrativo",
      porque: "Enquanto você não envia suas operações, a página mostra um exemplo para você entender o funcionamento.",
      faz: "Leva a Importar dados, onde você envia notas de corretagem ou o relatório da B3.",
      representa: "Dados fictícios: nenhum número desta tela é seu.",
      acao: () => ({ label: "Importar dados", href: "#/importar" }) },
    { id: "aviso-compras", secao: "Avisos", target: '[data-tour="aviso-compras"]', when: c => c.real && /^Há vendas sem/.test(c.t.limitations?.[0] || ""), titulo: "Faltam compras no histórico",
      porque: "Sem a compra, o preço médio do ativo é desconhecido e o lucro daquela venda não pode ser calculado.",
      faz: "Leva a Importar negociações, para completar o histórico desde a primeira compra.",
      representa: "Vendas que ficaram fora do cálculo por falta de dado.",
      numero: c => X.vendasSemCompra(c.ev, o(c)),
      acao: () => ({ label: "Importar negociações", href: "#/importar" }) },

    /* ---------------------------------------------------------------- C. cartões de resumo */
    { id: "kpi-imposto", secao: "Resumo do ano", target: '[data-tour="kpi-imposto"]', titulo: c => `Imposto estimado ${c.t.year}`,
      porque: "Mostra de uma vez quanto imposto sobre a bolsa o ano já gerou, para você planejar o caixa.",
      faz: "Soma as guias mensais. O detalhe de cada mês está na aba Apuração mensal.",
      representa: "Imposto de renda sobre ganhos em bolsa (guia DARF código 6015). É uma estimativa.",
      numero: c => X.impostoEstimado(c.t, c.rules, o(c)) },
    { id: "kpi-irrf", secao: "Resumo do ano", target: '[data-tour="kpi-irrf"]', titulo: "IRRF (dedo-duro)",
      porque: "A corretora retém um pouco de imposto em cada venda. Ele precisa ser descontado, senão você paga duas vezes.",
      faz: "Mostra o total retido no ano. O valor já é abatido automaticamente na apuração.",
      representa: "Imposto de renda retido na fonte: uma antecipação que avisa a Receita das suas vendas.",
      numero: c => X.irrf(c.t, c.rules, o(c)) },
    { id: "kpi-isentos", secao: "Resumo do ano", target: '[data-tour="kpi-isentos"]', titulo: "Ganhos isentos",
      porque: "Parte do lucro com ações não paga imposto, mas precisa ser declarada.",
      faz: "Soma o lucro dos meses em que as vendas de ações ficaram dentro do limite de isenção.",
      representa: c => `Lucro isento de imposto de renda, informado na declaração anual.${regraTxt(c, "BR-IRPF-RV-COMUM")}`,
      numero: c => X.ganhosIsentos(c.t, c.rules, o(c)) },
    { id: "kpi-confianca", secao: "Resumo do ano", target: '[data-tour="kpi-confianca"]', titulo: "Qualidade do cálculo",
      porque: "O imposto só é tão bom quanto os dados. Este índice avisa se falta algo antes de você pagar ou declarar.",
      faz: "Mostra a confiança de 0% a 100% e os prejuízos guardados. O detalhe completo fica mais abaixo.",
      representa: "Completude dos dados e das regras usadas. Não é garantia jurídica nem chance de acerto.",
      numero: c => X.confianca(c.t, c.ev, o(c)),
      acao: c => n(c.t.confidence) < 1 && (c.t.months || []).length ? { label: "Importar negociações", href: "#/importar" } : null },
    { id: "kpi-prejuizos", secao: "Resumo do ano", target: '[data-tour="kpi-prejuizos"]', titulo: "Prejuízos a compensar",
      porque: "Prejuízo em bolsa reduz o imposto de lucros futuros. Esquecê-lo é pagar imposto a mais.",
      faz: "Mostra o saldo de prejuízo de cada modalidade que ainda pode abater lucros.",
      representa: "Prejuízo acumulado por modalidade: operações comuns, day trade e FII.",
      numero: c => X.prejuizos(c.t, o(c)) },

    /* ---------------------------------------------------------------- D. abas */
    { id: "abas", secao: "Abas", target: '[data-tour="abas"]', titulo: "Quatro visões do mesmo cálculo",
      porque: "Cada pergunta tem um lugar: quanto pagar, como pagar, por quê e com base em qual regra.",
      faz: "Alterna entre Apuração mensal, Guias DARF/DARE, Eventos tributários e Regras e fontes.",
      representa: "O mesmo cálculo visto por mês, por guia, por operação e por regra." },
    { id: "tabela", secao: "Apuração mensal", tab: "resumo", target: '[data-tour="tabela-mensal"]', titulo: "Apuração mensal",
      porque: "O imposto da bolsa é apurado mês a mês. Cada mês tem sua guia e seu vencimento.",
      faz: "Lista os meses do ano com vendas, isenção, resultado, imposto, IRRF e guia.",
      representa: c => `${(c.t.months || []).length} meses com movimentação em ${c.t.year}.` },
    { id: "col-vendas", secao: "Apuração mensal", tab: "resumo", target: '[data-tour="col-vendas"]', titulo: "Mês e vendas de ações",
      porque: "O total vendido em ações no mês decide se o lucro é isento. Não é o lucro: é o valor das vendas.",
      faz: "Mostra a soma das vendas de ações de cada mês.",
      representa: "Valor bruto das vendas de ações no mês.",
      numero: c => { const m = exemplo(c); return m ? (c.demo ? X.SELO_DEMO : "") + `O mês com mais vendas foi ${X.mesBR(m.month)}: ${X.brl(m.sales_acoes)} em ações.` : null; } },
    { id: "col-isencao", secao: "Apuração mensal", tab: "resumo", target: '[data-tour="col-isencao"]', titulo: "Isenção",
      porque: "Se as vendas de ações do mês ficam no limite, o lucro com ações não paga imposto.",
      faz: "Marca cada mês como “até 20 mil” (isento) ou “tributável”.",
      representa: c => { const lim = (c.rules?.items || []).find(r => r.code === "BR-IRPF-RV-COMUM")?.parameters?.limite_isencao_vendas_mes; return `Limite mensal de vendas de ações${lim ? " de " + X.brl(lim) : ""}, sem contar day trade, FII e ETF.`; },
      numero: c => { const m = exemplo(c); return m ? (c.demo ? X.SELO_DEMO : "") + `${X.mesBR(m.month)} vendeu ${X.brl(m.sales_acoes)}: ${m.exempt ? "dentro do limite, isento" : "acima do limite, tributável"}.` : null; } },
    { id: "col-resultado", secao: "Apuração mensal", tab: "resumo", target: '[data-tour="col-resultado"]', titulo: "Resultado comum, day trade e FII",
      porque: "Cada modalidade tem alíquota própria e seus prejuízos não se misturam.",
      faz: "Mostra o lucro ou prejuízo de cada modalidade. A linha verde “+R$ isento” é o lucro que ficou fora do imposto.",
      representa: "Lucro ou prejuízo apurado por modalidade no mês." },
    { id: "col-ir", secao: "Apuração mensal", tab: "resumo", target: '[data-tour="col-ir"]', titulo: "IR bruto e IRRF",
      porque: "O imposto devido é o bruto menos o que a corretora já reteve.",
      faz: "Mostra o imposto antes do desconto (IR bruto) e a retenção do mês (IRRF).",
      representa: "Alíquota da modalidade aplicada sobre o lucro tributável, e a antecipação retida." },
    { id: "col-darf", secao: "Apuração mensal", tab: "resumo", target: '[data-tour="col-darf"]', titulo: "DARF 6015",
      porque: "É a guia que você paga ao banco. Atrasar gera multa e juros.",
      faz: "Mostra situação (aberto, vencido ou pago), valor e vencimento: último dia útil do mês seguinte à venda.",
      representa: c => { const min = (c.rules?.items || []).find(r => r.code === "BR-IRPF-RV-COMUM")?.parameters?.darf_valor_minimo; return `Guia de pagamento do imposto da bolsa. “Acumula” significa imposto abaixo de ${min ? X.brl(min) : "R$ 10"}, que soma com o mês seguinte.`; } },
    { id: "linha-exemplo", secao: "Apuração mensal", tab: "resumo", target: c => `[data-tour="tabela-mensal"] tr[data-month="${exemplo(c)?.month}"]`, when: c => !!exemplo(c), titulo: c => `Lendo uma linha: ${X.mesBR(exemplo(c).month)}`,
      porque: "Ler um mês completo mostra como todas as colunas se encaixam.",
      faz: "Usa o mês com mais vendas do ano como exemplo.",
      representa: "Uma apuração mensal completa, da venda até a guia.",
      numero: c => X.mesDarf(exemplo(c), c.rules, o(c)) },
    { id: "marcar-pago", secao: "Apuração mensal", tab: "resumo", target: "[data-paid]", when: c => c.real && temDarf(c), titulo: "Marcar pago / desfazer",
      porque: "O sistema precisa saber o que você já pagou para parar de avisar e para contar o valor certo.",
      faz: "Só registra o pagamento no AURION. Não paga nada nem acessa o seu banco. “Desfazer” volta atrás.",
      representa: "O controle das guias que você já quitou." },
    { id: "gerar-darf", secao: "Apuração mensal", tab: "resumo", target: "[data-guia]", when: c => (c.t.months || []).some(m => m.darf && m.darf.status !== "pago"), titulo: "Gerar DARF",
      porque: "Preencher a guia à mão é onde mais se erra: código, período e valor.",
      faz: "Abre a aba Guias já com código 6015, mês e valor preenchidos.",
      representa: "Atalho do imposto calculado para a guia de pagamento." },

    /* ---------------------------------------------------------------- guias */
    { id: "guia-tipo", secao: "Guias DARF/DARE", tab: "guias", target: '[data-tour="guia-tipo"]', titulo: "DARF ou DARE",
      porque: "Cada esfera de governo usa sua própria guia. A guia errada não quita o tributo.",
      faz: "Escolhe entre DARF, para tributos federais como o IR da bolsa, e DARE, para tributos estaduais como ITCD e ICMS.",
      representa: "Documento de arrecadação federal (DARF) ou estadual (DARE)." },
    { id: "guia-form", secao: "Guias DARF/DARE", tab: "guias", target: '[data-tour="guia-form"]', titulo: "Dados da guia",
      porque: "Código de receita errado faz o pagamento cair em outro tributo.",
      faz: "Confere o código de receita, os dígitos do CPF ou CNPJ, o período de apuração e o valor principal.",
      representa: "Os campos oficiais da guia de pagamento." },
    { id: "guia-resultado", secao: "Guias DARF/DARE", tab: "guias", target: '[data-tour="guia-resultado"]', titulo: "Resultado: vencimento, multa e juros",
      porque: "Pagar depois do vencimento exige somar multa e juros; sem isso, a guia não quita a dívida.",
      faz: "Mostra o vencimento legal e, se houver atraso, a multa de 0,33% por dia (limitada a 20%) e os juros pela Selic acumulada mais 1% no mês do pagamento.",
      representa: "Acréscimos legais sobre tributo federal pago em atraso.",
      numero: c => { const e = c.guias?.() || {}; return X.guiaResultado(e.ultimo, e.lista, o(c)); } },
    { id: "guia-lista", secao: "Guias DARF/DARE", tab: "guias", target: '[data-tour="guia-lista"]', titulo: "Guias geradas",
      porque: "Guardar o histórico evita gerar a mesma guia duas vezes e ajuda na conferência.",
      faz: "Lista as guias geradas, com situação. O código de barras oficial é emitido no Sicalc da Receita.",
      representa: "Seu histórico de guias de pagamento." },

    /* ---------------------------------------------------------------- eventos e regras */
    { id: "eventos", secao: "Eventos tributários", tab: "eventos", target: '[data-tour="eventos"] article', when: c => (c.ev?.items || []).length > 0, titulo: "Cada venda vira um evento",
      porque: "Para conferir o imposto, é preciso ver a conta de cada operação.",
      faz: "Mostra valor de venda, custo, resultado, regra aplicada (código e versão), fontes e origem do dado.",
      representa: "O registro auditável de cada operação tributável.",
      numero: c => X.evento(c.ev.items[0], o(c)) },
    { id: "evento-pendente", secao: "Eventos tributários", tab: "eventos", target: '[data-tour="eventos"] [data-ev-status="pendente_dado"]', when: c => (c.ev?.items || []).some(e => e.status === "pendente_dado"), titulo: "Situação e confiança do evento",
      porque: "Mostra exatamente qual operação está segurando a qualidade do cálculo.",
      faz: "Classifica o evento como calculado, isento ou pendente de dado, com a confiança de cada um.",
      representa: "Confiança por operação: 100% normal, 90% day trade inferido, 80% classe deduzida, 30% sem custo. O cartão do resumo usa o menor valor entre os meses, não a média.",
      numero: c => X.evento(c.ev.items.find(e => e.status === "pendente_dado"), o(c)),
      acao: () => ({ label: "Importar negociações", href: "#/importar" }) },
    { id: "regras", secao: "Regras e fontes", tab: "regras", target: '[data-tour="regras"] article', titulo: "Regras e fontes",
      porque: "Você pode conferir de onde vem cada alíquota, limite e prazo usado no cálculo.",
      faz: "Mostra cada regra com versão, vigência, fórmula, exceções e links das fontes oficiais. Regras “pendentes” não entram no cálculo.",
      representa: c => `${(c.rules?.items || []).length} regras versionadas do catálogo ${c.rules?.catalog?.catalog_version || ""}.`.replace(" .", ".") },

    /* ---------------------------------------------------------------- E. blocos abaixo */
    { id: "premissas", secao: "Base do cálculo", target: '[data-tour="premissas"]', titulo: "Premissas",
      porque: "Todo cálculo parte de hipóteses. Deixá-las escritas evita surpresas.",
      faz: "Lista as bases usadas: quais dados entram e como o preço médio é formado.",
      representa: c => `${(c.t.premises || []).length} premissas deste cálculo.` },
    { id: "limitacoes", secao: "Base do cálculo", target: '[data-tour="limitacoes"]', titulo: "Limitações e snapshot",
      porque: "Saber o que o cálculo não cobre evita confiar nele onde ele não vale.",
      faz: "Lista o que fica de fora (opções, termo, futuros, aluguel, proventos e eventos corporativos) e mostra o snapshot.",
      representa: c => `Snapshot ${String(c.t.snapshot_hash || "").slice(0, 16)}… é a impressão digital das entradas: mesmas entradas e mesma versão da regra dão o mesmo resultado.` },
    { id: "qualidade", secao: "Base do cálculo", target: '[data-tour="qualidade"]', when: c => c.real, titulo: "Qualidade do cálculo — detalhe",
      porque: "Mostra fator por fator o que está completo e o que falta.",
      faz: "Avalia custo de aquisição, classe dos ativos, versão da regra e escopo, com ✓ ou ! e o que fazer para elevar.",
      representa: "O diagnóstico completo por trás do índice de confiança.",
      numero: c => X.confianca(c.t, c.ev, o(c)) },
    { id: "auditoria", secao: "Base do cálculo", target: '[data-tour="auditoria"]', when: c => c.real, titulo: "Auditoria do cálculo",
      porque: "Numa fiscalização, você precisa provar como chegou ao valor.",
      faz: "“Baixar Excel de auditoria” gera o arquivo para o contador. “Reprocessar e conferir” refaz o cálculo e confirma o mesmo resultado.",
      representa: "Código do cálculo, versão do motor e das regras e a impressão das entradas." },
    { id: "irpf", secao: "Base do cálculo", target: '[data-tour="irpf"]', when: c => c.real, titulo: "Relatório para a declaração",
      porque: "A declaração anual pede os mesmos números em fichas diferentes.",
      faz: "Organiza renda variável, rendimentos isentos e bens e direitos, e baixa em Excel.",
      representa: "O apoio à declaração do IRPF, gerado do mesmo cálculo." },
    { id: "ajustes", secao: "Base do cálculo", target: '[data-tour="ajustes"]', when: c => c.real, titulo: "Ajustes da apuração",
      porque: "Prejuízos de anos anteriores reduzem o imposto deste ano, mas o sistema não os conhece sozinho.",
      faz: "Recebe o prejuízo acumulado até 31/12 do ano anterior, por modalidade. “Salvar e recalcular” refaz a apuração. O tour não salva nada.",
      representa: "Onde achar o valor: declaração anterior (ficha Renda Variável) ou controle do seu contador." },

    /* ---------------------------------------------------------------- F. encerramento */
    { id: "resumo", secao: "Encerramento", titulo: "Seus pontos de atenção",
      final: c => { const r = X.resumoFinal(c.t, c.ev, c.hoje, o(c)); return { intro: c.demo ? X.SELO_DEMO + "Resumo do exemplo:" : "Com base nos seus dados de hoje:", itens: r.itens, vazio: "Sua apuração está completa para os dados enviados." }; } },
  ];
}
